dependencies:
  espressif/esp-tflite-micro:
    version: 1.3.3~1
  espressif/esp32-camera:
    version: 2.0.15
  espressif/mdns:
    version: 1.8.2
  espressif/esp_wifi_remote:
    version: 0.10.2
    rules:
      - if: "target in [esp32h2, esp32p4]"
  espressif/eppp_link:
    version: 0.2.0
    rules:
      - if: "target in [esp32h2, esp32p4]"
  espressif/esp_hosted:
    version: 2.0.11
    rules:
      - if: "target in [esp32h2, esp32p4]"
